[package]
name = "oxy2fa"
version = "0.0.1"
authors = ["lonnen <chris.lonnen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
ring = "^0.16"